spring:
  main:
    lazy-initialization: true
  application:
    name: webclient-integration-test

generator:
  resttemplate:
    clients:
      client-one:
        base-url: http://localhost:8381/client-one
      client-two:
        base-url: http://localhost:8381/client-two
      client-three:
        base-url: http://localhost:8381/client-three
        default-headers:
          x-default-header: default
      client-four:
        base-url: http://localhost:8381/client-four
        authentication:
          basic-auth:
            username: Jon Snow
            password: Daenerys Targaryen
      client-five:
        base-url: http://localhost:8381/client-five