spring:
  main:
    lazy-initialization: true
  application:
    name: webclient-integration-test

generator:
  webclient:
    clients:
      client-one:
        base-url: http://localhost:8382/client-one
      client-two:
        base-url: http://localhost:8382/client-two
      client-three:
        base-url: http://localhost:8382/client-three
        default-headers:
          x-default-header: default
      client-four:
        base-url: http://localhost:8382/client-four
        authentication:
          basic-auth:
            username: Jon Snow
            password: Daenerys Targaryen